### ISSUE TITLE
Quais são os melhores lugares pra estudar?

### ISSUE THREAD

**Issue by Valerieps** [girls-support-girls/survival-guide#1]
Biblioteca, em casa? Quais biblios são boas?

**Comment by innng** [comment]
Biblioteca da pós de física. 
* Silêncio
* Mesas individuais
* Lugar legal
* Tomada 3 pinos

Só não sei dizer como chegar lá, mas super recomendo.

**Comment by Valerieps** [comment]
A biblio da física é muito boa mesmo. Fica no terceiro andar. Só seguir as placas "biblioteca PPG" (programa de pós-graduação)

**Comment by Valerieps** [comment]
Além disso tem a biblioteca da pós da computação. Só pegar o elevador para o quarto andar que sai na porta dela
