### ISSUE TITLE
Sugestões de canais de video aulas

### ISSUE THREAD

**Issue by Valerieps** [girls-support-girls/survival-guide#2]
Cálculo, GAAL e PDS 1

**Comment by mirianfsilva** [comment]
[3Blue1Brown](https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw)
Esse canal é incrível, e um dos meus preferidos. Super útil pra calculo I e algebra linear (que engloba gaal) no geral. Ele explica a matemática por meio de animações que faz a gente ter uma outra perspectiva do cálculo e da álgebra. É lindo.

**Comment by martinelles** [comment]
Pra PDS1 recomendo o curso de Logica de Programação do [Curso em Video](https://www.youtube.com/user/cursosemvideo)

**Comment by martinelles** [comment]
[Playlist do curso de Logica de Programação](https://www.youtube.com/watch?v=8mei6uVttho&list=PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV)
