### ISSUE TITLE
Onde ficam as salas de colegiado, secretária e coordenação do meu curso? 

### ISSUE THREAD

**Issue by mirianfsilva** [girls-support-girls/survival-guide#5]
Matemática Computacional, Sistemas de Informação e Ciência da Computação.

**Comment by Valerieps** [comment]
Sistemas de INformação:
   Sala do Colegiado: Fica no DCC (prédio branco), 5º andar
   Secretaria: fica na frente da sala 2077, uma janelinha numa quina
