### ISSUE TITLE
Como alterar minha página do DCC

### ISSUE THREAD

**Issue by IVictorino** [girls-support-girls/survival-guide#6]
Como posso alterar minha página do DCC e estilizá-la?
Todos os links do crc.dcc.ufmg.br/howto estão indisponíveis

**Comment by Valerieps** [comment]
Olá!
1- O primeiro passo é ter um **login do DCC**, que é diferente do login da Minha UFMG. Esse login você cria junto ao CRC - Centro de Recursos Computacionais, que fica no ICEx, segundo andar, que fica na esquina com a sala 2011.

**Comment by Valerieps** [comment]
Quando criar esse login, voce vai ter acesso a:
- Um espaço no servidor, que é onde vai colocar seu site
- Acesso remoto a todas as máquinas do DCC
- Uma caixa de email por onde receberá avisos do DCC e vagas de IC e estágio

**Comment by Valerieps** [comment]
Vou passar o acesso a esse espaço em servidor por meio do terminal em Linux. Se alguém souber fazer esse acesso de outra forma, comenta aqui.
(https://www.crc.dcc.ufmg.br/servicos/website/start)

2 - No terminal, faça um acesso SSH:
ssh nome_do_usuario@login.dcc.ufmg.br

Você vai entrar na máquina chamada Mica. Nela, você não pode instalar nenhum programa e o seu acesso é monitorado.

**Comment by Valerieps** [comment]
3- Coloque os arquivos na pasta public_html. Eu uso [sftp ](https://www.digitalocean.com/community/tutorials/como-utilizar-o-sftp-para-transferir-arquivos-com-seguranca-com-um-servidor-remoto-pt)para a transferência.

É mais fácil criar os arquivos na sua máquina local e subir apenas quando estiver do jeito que você quer. Para quem um site sem muito esforço, pode usar algum template dentre os milhões que existem 3 - disponíveis aí pra nas interwebs
